#ifndef SRC_EVENT_H
#define SRC_EVENT_H

enum Event {
	EVENT_PLAYER_JOIN,
	EVENT_PLAYER_PART,
	EVENT_BOMB_ADD,
	EVENT_BOMB_DIED,
	EVENT_BOMB_EXPLODED,
	EVENT_SUBJECT_DIED,
	EVENT_INPUT_PLAYER_FORWARD,
	EVENT_INPUT_PLAYER_BACKWARD,
	EVENT_INPUT_PLAYER_LEFT,
	EVENT_INPUT_PLAYER_RIGHT,
	EVENT_INPUT_BOMB_ADD,
	EVENT_TILE_CHANGE
};

#endif
